# Generated by Django 5.2.5 on 2025-08-07 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publishd_at',
            new_name='published_at',
        ),
    ]
